const garbageWords = [
    'i’m going to',
    "i have to",
    "do you think",
    "what are you",
    "do you think",
    "what do you",
    "i can do",
    "be able to",
    "can do it",
    "you can do",
    "you’re going to",
    "should i do",
    "i have no",
    "what should i",
    "i won’t let",
    "want you to",
    "are you doing",
    "the one who",
    "why are you",
    "what kind of",
    "you think you’re",
    "no matter how",
    "back into a",
    "the hell are you",
    "we’re going to",
    "you very much",
    "you want to",
    "take care of",
    "what did you",
    "going to be",
    "going to do",
    "you have a",
    "have to do",
    "as long as",
    "no need to",
    "out of my",
    "do you think you’re",
    "why don’t you",
    "even if you", 'know what i', 'about to do', 'a long time', 'it was like', 'it can’t be',
    'right now i', 'it’s like a', 'i was going', 'where is he', 'i can still',
    'way you can', 'could it be', 'are so very', 'that was a', 'but i have',
    'to kill me', 'you to the', 'so i can’t', 'this is it', 'if i don’t',
    'what it is', 'i can feel', 'any of the', 'you got it', 'i wish you',
    'want me to', 'you get to', 'to give it', 'so what if', 'if you get',
    'is it that', 'what i can', 'is that so', 'this is no', 'to the end',
    'the god of', 'that i was', 'if it was', 'to take a', 'i think i',
    'it with a', 'but i was', 'on top of', 'and i are', 'all i did', 'for us to',
    'has to be', 'i knew it', 'no good i', 'me in the', 'on to the', 'it was a',
    'can i do', 'i was so', 'go of me', 'so i was',"so i can", "i’m sure the", "realm of the", "have to wake", "going to end", "you say that",
"you piece of", "back to the", "one of them", "but i’m not", "no one ever",
"glad to see", "to tell you", "that i have", "shut up and", "is this the",
"look at you", "like you to", "since i was", "if you have","i don’t mind","i couldn’t be", "why would you", "thanks to the", "going to give", "going to work",
"don’t die on", "i was hoping", "the smell of", "you can have", "i’ll have to",
"a demon with", "i wonder how", "you may have", "all right to", "as long as i",
"you think so", "you get away", "do you still", "if it hadn’t", "the power of",
"is making me", "don’t have a", "all three of", "of the night", "the crime of",
"you guys are", "have to take", "to deal with", "i don’t need", "all over the",
"as i thought", "up right now", "can do it you", "have to do it", "long as i", "that i could", "can do it you",
"the middle of", "don’t you get", "no that’s not", "can’t take it", "and then i’ll",
"to speak with", "going on here", "be able to do", "the other one", "the village is",
"you in the end", "are you gonna", "i’ll make you", "going to have", "he’s going to",
"going to keep", "make sure you","i haven’t been", "those who have", "you can’t even", "i’ll be taking", "going to leave",
"you can become", "who’s going to", "get out of the", "you you’re the", "that all right",
"swamp oni ngh…", "didn’t want to", "demon with the", "how do you like", "are we going to",
"one of you", "to do what", "i was sure", "as well as", "no i don’t", "i was told",
"there is a", "so this is", "as much as", "no one who", "i tell you", "the top of",
"it you can", "all of you", "no time to", "you in the", "am i right", "i can get",
"to have a", "give it a", "up to the", "as i can", "to do is", "is it a", "what’s up with", "ngh… ngh… ngh…", "going to make", "that’s what i", "i wonder what",
"i’m sure that", "i swear i’ll", "that i don’t", "to the demon", "i can’t take",
"that’s why i", "up with that", "that i can’t", "do you have", "while i was",
"don’t do it", "a demon but", "you i can’t", "i can’t get", "the rest of",
"i’ve got to", "the hell up", "i hear that", "i thought i", "go back to",
"so you can", "to do that", "to see you", "i can’t do", "the one to",
"in such a", "if i were", "you did a", "it my all", "do it you", "i had no",
"i was a", "to take care of", "i’m not letting", "the hell out of", "right i’m going",
"never going to", "would you like", "i’m not giving", "you have to do", "i couldn’t do",
"this time i’m", "it’s not just", "you know that", "come on let’s", "get out of my",
"just going to", "i’m sorry i’m", "you’ve got to", "come on come", "hurry up and",
"just look at", "i’m about to", "have to get", "it could be", "it won’t be",
"is going to", "right i can", "no need for", "is about to",
"deal with it deal with it deal with it",
"what should i do what should i do",
"can’t tell you i can’t tell you",
"do you think you can",
"what do you mean by",
"i’m sorry i’m sorry", "we going to", "do you like", "and then i", "swamp oni ngh",
"(thoughts) i don’t", "hand oni (thoughts)",
"deal with it deal with it deal with", "with it deal with it deal with it",
"you must be", "up will you", "hell out of","the hell are","hell are you", "deal with it deal with it",
"deal with it deal with it deal",
"with it deal with it deal with",
"it deal with it deal with it", "deal with it deal with",
"with it deal with it",
"with it deal with it deal",
"it deal with it deal with", "deal with it deal",
"with it deal with",
"it deal with it",
"it deal with it deal", "with it deal",
"it deal with", "now i can", "let go of", "a way to", "to do it",
"have to go", "able to do", "i can tell", "a demon and",
"i’d like to", "i know what", "it would be", "you can’t do",
"i wonder if", "to become a", "you think you", "all right i’m",
"i can do this", "just have to", "we have to", "i want to",
"i can see", "this is a", "what am i", "i get it",
"all of a", "i don’t think", "it’s going to", "am i going to",
"i’ve got a", "and i will", "that i can", "what is it",
"and i can’t", "all right i", "i want you to", "it to me",
"a lot of", "it’s not like", "as soon as", "if i can",
"i did it", "was able to", "you have to", "even if i",
"you no matter what", "you all right", "thank you for", "get out of"
];

export default garbageWords;